name: xadrez-paradigmas
version: 0.1.0.0
github: "githubuser/xadrez-paradigmas"
license: BSD-3-Clause
author: "Author name here"
maintainer: "example@example.com"
copyright: "2024 Author name here"

extra-source-files:
  - README.md
  - CHANGELOG.md

description: Please see the README on GitHub at <https://github.com/githubuser/xadrez-paradigmas#readme>

dependencies:
  - base >= 4.7 && < 5
  - process
  - gloss
  - gloss-juicy
  - random

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  exposed-modules:
    - Check
    - CheckMate
    - Gui
    - ProcessarMovimento
    - Tabuleiro
    - Utils
    - ValidacaoMovimento
    - AI
  source-dirs: src
  ghc-options:
    - -Wall
    - -Wcompat
    - -Widentities
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wmissing-export-lists
    - -Wmissing-home-modules
    - -Wpartial-fields
    - -Wredundant-constraints
  build-depends:
    - base >=4.7 && <5
    - process
    - gloss
    - gloss-juicy
    - random
  default-language: Haskell2010

executables:
  xadrez-paradigmas-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
      - -Wcompat
      - -Widentities
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wmissing-export-lists
      - -Wmissing-home-modules
      - -Wpartial-fields
      - -Wredundant-constraints
    build-depends:
      - xadrez-paradigmas

tests:
  xadrez-paradigmas-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
      - -Wcompat
      - -Widentities
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wmissing-export-lists
      - -Wmissing-home-modules
      - -Wpartial-fields
      - -Wredundant-constraints
    build-depends:
      - xadrez-paradigmas
